on: push
jobs:
    first-job:
        runs-on: ubuntu-linux
        container: node:14
        steps:
            - run: node --version
            - run: npm --version
            - run: java -version
